require "forwardable"

require "faraday"
require "virtus"

require "affirm/client"
require "affirm/charge"
require "affirm/configuration"
require "affirm/success_result"
require "affirm/failure_result"
require "affirm/objects/event"
require "affirm/objects/contact"
require "affirm/objects/address"
require "affirm/objects/billing"
require "affirm/objects/shipping"
require "affirm/objects/discount"
require "affirm/objects/item"
require "affirm/objects/order"
require "affirm/responses/auth"
require "affirm/responses/capture"
require "affirm/responses/void"
require "affirm/responses/refund"
require "affirm/responses/update"
require "affirm/responses/error"

require "affirm/version"
